build:
  image: golang:1.8
  # You can list files or directories to copy to application directory
  # (/opt/nuclio) on the docker container
  copy:
      - key.txt
  # You can provide commands to run (will run after copy)
  commands:
      - apt install -y jq
  # or provide your own install script (will run after commands)
  script: install.sh
